version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-type: "all"
    open-pull-requests-limit: 10
    security-updates: true
