name: Disable Deployment for New Branches

on:
  push:
    branches-ignore:
      - main

jobs:
  disable-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Get current branch name
        run: echo "Current branch is ${{ github.ref_name }}"

      - name: Disable auto-deploy for new branch
        run: |
          BRANCH_NAME=${{ github.ref_name }}

          if jq -e ".git.deploymentEnabled[\"$BRANCH_NAME\"]" vercel.json > /dev/null; then
            echo "Branch $BRANCH_NAME already exists in vercel.json, skipping."
          else
            echo "Disabling auto-deploy for branch $BRANCH_NAME"
            jq ".git.deploymentEnabled[\"$BRANCH_NAME\"] = false" vercel.json > tmp.json && mv tmp.json vercel.json

            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add vercel.json

            if git diff --cached --quiet; then
              echo "No changes to commit, skipping."
            else
              git commit -m "Disable auto deploy for branch $BRANCH_NAME"
              git push
            fi
          fi
